global:
  scrape_interval: 5s  # Scrape every 15 seconds

scrape_configs:
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['host.containers.internal:5000']  # Replace with the actual IP or hostname of your Node.js app
